version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: contact-keeper-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - contact-keeper-network
    restart: unless-stopped

  # Optional: MongoDB Express (Web UI for MongoDB)
  mongo-express:
    image: mongo-express:latest
    container_name: contact-keeper-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - contact-keeper-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  contact-keeper-network:
    driver: bridge
